import Foundation
#if os(Linux)
import Glibc
#else
import Darwin
#endif

/// Methods for discovering Sonos devices on the network.
///
/// SoCo has two discovery strategies. Normal discovery uses UPnP/SSDP multicast,
/// which is the fast and preferred path. A TCP scan of attached IPv4 networks is
/// also available as a fallback for networks where multicast is filtered or
/// otherwise unreliable.
public enum Discovery {
    /// UPnP discovery search used by Sonos Zone Players.
    ///
    /// Only Zone Players should respond, given the value of ST. As the original
    /// SoCo implementation notes, broken devices do sometimes answer searches
    /// they should not, so `discover` additionally checks the response for the
    /// requested Sonos household marker before accepting it.
    public static let playerSearch = """
    M-SEARCH * HTTP/1.1\r
    HOST: 239.255.255.250:1900\r
    MAN: \"ssdp:discover\"\r
    MX: 1\r
    ST: urn:schemas-upnp-org:device:ZonePlayer:1\r
    \r
    """

    /// Options used by the TCP network-scan fallback.
    public struct NetworkScanOptions: Sendable, Equatable {
        public var multiHousehold: Bool
        public var maxThreads: Int
        public var scanTimeout: TimeInterval
        public var minNetmask: Int
        public var networksToScan: [String]?

        public init(
            multiHousehold: Bool = false,
            maxThreads: Int = 256,
            scanTimeout: TimeInterval = 0.5,
            minNetmask: Int = 24,
            networksToScan: [String]? = nil
        ) {
            self.multiHousehold = multiHousehold
            self.maxThreads = maxThreads
            self.scanTimeout = scanTimeout
            self.minNetmask = minNetmask
            self.networksToScan = networksToScan
        }
    }

    /// Discover Sonos zones on the local network.
    ///
    /// Return a set of `SoCo` instances for each zone found. Include invisible
    /// zones (bridges and slave zones in stereo pairs) when `includeInvisible`
    /// is true. This blocks for up to `timeout` seconds, after which it returns
    /// `nil` if no zones were found.
    ///
    /// The presence of a `SoCo` object in the returned set is not a guarantee
    /// that the associated Sonos player is currently contactable. The set is
    /// generated by interrogating the first discovered player for the current
    /// topology, and that data can lag the actual state of the system, for
    /// example if a speaker has just been switched off.
    ///
    /// Discovery operates by sending UDP multicast datagrams. `interfaceAddress`
    /// is the dotted-quad address to use as IP_MULTICAST_IF. If omitted, all
    /// qualified local IPv4 interfaces are used.
    ///
    /// - Important: On iOS/macOS applications, the host app must provide an
    ///   `NSLocalNetworkUsageDescription` entry and receive local-network access
    ///   from the user. The Swift package itself cannot add an app Info.plist key.
    public static func discover(
        timeout: TimeInterval = 5,
        includeInvisible: Bool = false,
        interfaceAddress: String? = nil,
        householdID: String = "Sonos",
        allowNetworkScan: Bool = false,
        networkScanOptions: NetworkScanOptions = .init()
    ) throws -> Set<SoCo>? {
        let addresses: Set<String>
        if let interfaceAddress {
            guard parseIPv4(interfaceAddress) != nil else {
                throw SoCoError.invalidArgument(
                    "\(interfaceAddress) is not a valid IP address string"
                )
            }
            addresses = [interfaceAddress]
        } else {
            addresses = findIPv4Addresses()
            if addresses.isEmpty {
                return nil
            }
        }

        // Create one socket for each interface. A multicast interface is a
        // socket-level property, so using multiple local interfaces requires
        // multiple sockets just as it does in Python SoCo.
        var sockets: [Int32] = []
        for address in addresses {
            if let fd = createDiscoverySocket(interfaceAddress: address) {
                sockets.append(fd)
            }
        }
        defer { sockets.forEach { systemClose($0) } }

        // Send a few times to each socket. UDP is unreliable.
        for _ in 0..<3 {
            var surviving: [Int32] = []
            for fd in sockets {
                if sendDiscovery(fd: fd) {
                    surviving.append(fd)
                } else {
                    systemClose(fd)
                }
            }
            sockets = surviving
        }

        if sockets.isEmpty {
            return nil
        }

        let start = DispatchTime.now().uptimeNanoseconds
        let timeoutNanos = UInt64(max(0, timeout) * 1_000_000_000)
        let householdBytes = Array(householdID.utf8)

        while true {
            // Use a monotonic clock. The old Python source calls out that its
            // `time.time()` loop was sensitive to wall-clock adjustments; Swift
            // does not need to preserve that historical limitation.
            let elapsed = DispatchTime.now().uptimeNanoseconds - start
            if elapsed > timeoutNanos {
                break
            }

            // Keep the poll interval no greater than 100ms so the requested
            // discovery timeout is not exceeded by much if this loop repeats.
            let remaining = timeoutNanos > elapsed ? timeoutNanos - elapsed : 0
            let pollMillis = Int32(min(100, max(0, Int(remaining / 1_000_000))))
            var pollfds = sockets.map {
                pollfd(fd: $0, events: Int16(POLLIN), revents: 0)
            }
            let ready = systemPoll(&pollfds, nfds_t(pollfds.count), pollMillis)
            if ready <= 0 { continue }

            for item in pollfds where (item.revents & Int16(POLLIN)) != 0 {
                if let response = receiveDiscovery(fd: item.fd),
                   containsBytes(response.data, householdBytes)
                {
                    // Now we have an IP, build a SoCo instance and query that
                    // player for the topology to find the others. It is much
                    // more efficient to rely on a Zone Player's ability to find
                    // its peers than to wait for every SSDP response ourselves.
                    let zone = try SoCoConfig.socoFactory(response.ipAddress)
                    return includeInvisible ? try zone.allZones() : try zone.visibleZones()
                }
            }
        }

        if allowNetworkScan {
            if householdID == "Sonos" {
                return try scanNetwork(
                    includeInvisible: includeInvisible,
                    options: networkScanOptions
                )
            }
            return try scanNetworkByHouseholdID(
                householdID,
                includeInvisible: includeInvisible,
                options: networkScanOptions
            )
        }
        return nil
    }

    /// Return any visible SoCo device, for when it does not matter which one.
    ///
    /// Try to obtain an existing instance, or use discovery if necessary. This
    /// assumes a previously-created instance has not since left the network.
    public static func anySoCo(
        allowNetworkScan: Bool = false,
        networkScanOptions: NetworkScanOptions = .init()
    ) throws -> SoCo? {
        if let existing = SoCoRegistry.shared.existing().first(where: {
            (try? $0.isVisible()) == true
        }) {
            return existing
        }
        return try discover(
            allowNetworkScan: allowNetworkScan,
            networkScanOptions: networkScanOptions
        )?.first
    }

    /// Return a visible device by player name.
    public static func byName(
        _ name: String,
        allowNetworkScan: Bool = false,
        networkScanOptions: NetworkScanOptions = .init()
    ) throws -> SoCo? {
        guard let devices = try discover(
            allowNetworkScan: allowNetworkScan,
            networkScanOptions: networkScanOptions
        ) else {
            return nil
        }
        return try findByName(name, in: devices)
    }

    /// Scan all attached networks for Sonos devices.
    ///
    /// Public, loopback and link-local ranges are excluded when attached
    /// networks are discovered automatically, and `minNetmask` constrains the
    /// search space. Alternatively, `networksToScan` can provide explicit CIDR
    /// strings, in which case `minNetmask` is ignored.
    ///
    /// This is intended for cases where normal multicast discovery does not
    /// work. A scan can miss a real speaker because an ARP lookup does not finish
    /// within the timeout; retry with a longer `scanTimeout` if necessary.
    public static func scanNetwork(
        includeInvisible: Bool = false,
        options: NetworkScanOptions = .init()
    ) throws -> Set<SoCo>? {
        let networks: [IPv4Network]
        if let specified = options.networksToScan, !specified.isEmpty {
            // Invalid entries are deliberately ignored, matching Python SoCo.
            networks = specified.compactMap(IPv4Network.init)
        } else {
            networks = Array(findIPv4Networks(minNetmask: options.minNetmask))
        }

        guard !networks.isEmpty else { return nil }

        let foundIPs = scanIPAddresses(
            networks: networks,
            maxThreads: options.maxThreads,
            socketTimeout: options.scanTimeout,
            multiHousehold: options.multiHousehold,
            portChecker: { checkIPAndPort($0, port: SoCoConfig.sonosPort, timeout: $1) },
            sonosChecker: { isSonos($0) }
        )
        guard !foundIPs.isEmpty else { return nil }

        var zones = Set<SoCo>()
        for ipAddress in foundIPs {
            let zone = try SoCoConfig.socoFactory(ipAddress)
            let householdZones = includeInvisible ? try zone.allZones() : try zone.visibleZones()
            zones.formUnion(householdZones)

            // Stop after the first discovered household unless exhaustive
            // multi-household discovery was requested.
            if !options.multiHousehold { break }
        }
        return zones.isEmpty ? nil : zones
    }

    /// Convenience function to find zones in one Sonos household.
    public static func scanNetworkByHouseholdID(
        _ householdID: String,
        includeInvisible: Bool = false,
        options: NetworkScanOptions = .init()
    ) throws -> Set<SoCo>? {
        var exhaustive = options
        // multi_household must be set to true, otherwise the scanner can stop
        // after finding a speaker belonging to some other household.
        exhaustive.multiHousehold = true
        guard let zones = try scanNetwork(
            includeInvisible: includeInvisible,
            options: exhaustive
        ) else {
            return nil
        }
        let matches = try zones.filter { try $0.householdID().contains(householdID) }
        return Set(matches)
    }

    /// Find all Sonos household IDs on the attached networks.
    public static func scanNetworkGetHouseholdIDs(
        options: NetworkScanOptions = .init()
    ) throws -> Set<String> {
        var exhaustive = options
        exhaustive.multiHousehold = true
        guard let zones = try scanNetwork(includeInvisible: true, options: exhaustive) else {
            return []
        }
        return try Set(zones.map { try $0.householdID() })
    }

    /// Use network scanning to find a visible zone by its name.
    ///
    /// If multiple zones have the same name, only one is returned. Supplying a
    /// household ID disambiguates same-named zones across households.
    public static func scanNetworkGetByName(
        _ name: String,
        householdID: String? = nil,
        options: NetworkScanOptions = .init()
    ) throws -> SoCo? {
        var exhaustive = options
        exhaustive.multiHousehold = true
        guard let zones = try scanNetwork(includeInvisible: false, options: exhaustive) else {
            return nil
        }
        for zone in zones where try zone.playerName() == name {
            if let householdID {
                if try zone.householdID() == householdID { return zone }
            } else {
                return zone
            }
        }
        return nil
    }

    /// Use network scanning to find any visible zone, optionally in one household.
    public static func scanNetworkAnySoCo(
        householdID: String? = nil,
        options: NetworkScanOptions = .init()
    ) throws -> SoCo? {
        var adjusted = options
        if householdID != nil { adjusted.multiHousehold = true }
        guard let zones = try scanNetwork(includeInvisible: false, options: adjusted) else {
            return nil
        }
        guard let householdID else { return zones.first }
        for zone in zones where try zone.householdID() == householdID { return zone }
        return nil
    }

    /// Find only contactable players in a set of SoCo objects.
    ///
    /// Contact attempts run in parallel to minimise delays when one or more
    /// players have gone offline. Unlike Python's mutable-set implementation,
    /// Swift's value-semantic input set is not consumed by this operation.
    public static func contactable(_ speakers: Set<SoCo>?) -> Set<SoCo> {
        guard let speakers, !speakers.isEmpty else { return [] }
        let candidates = Array(speakers)
        let result = LockedSet<SoCo>()
        DispatchQueue.concurrentPerform(iterations: candidates.count) { index in
            let speaker = candidates[index]
            if (try? speaker.isVisible()) != nil {
                result.insert(speaker)
            }
        }
        return result.value
    }
}

// MARK: - IPv4 helpers

/// A compact IPv4 CIDR value. The original Python implementation uses
/// `ipaddress.IPv4Network`; this supplies the subset needed by discovery without
/// adding a third-party package to SoCoKit.
internal struct IPv4Network: Hashable, CustomStringConvertible, Sendable {
    let networkAddress: UInt32
    let prefixLength: Int

    init?(_ cidr: String) {
        let pieces = cidr.split(separator: "/", omittingEmptySubsequences: false)
        guard pieces.count == 1 || pieces.count == 2,
              let address = parseIPv4(String(pieces[0]))
        else { return nil }

        let prefix: Int
        if pieces.count == 2 {
            guard let parsed = Int(pieces[1]), (0...32).contains(parsed) else { return nil }
            prefix = parsed
        } else {
            prefix = 32
        }

        self.prefixLength = prefix
        self.networkAddress = address & Self.mask(prefix)
    }

    init(address: String, prefixLength: Int) {
        let addressValue = parseIPv4(address) ?? 0
        let prefix = min(32, max(0, prefixLength))
        self.prefixLength = prefix
        self.networkAddress = addressValue & Self.mask(prefix)
    }

    var broadcastAddress: UInt32 { networkAddress | ~Self.mask(prefixLength) }
    var addressCount: UInt64 { UInt64(broadcastAddress) - UInt64(networkAddress) + 1 }
    var description: String { "\(formatIPv4(networkAddress))/\(prefixLength)" }

    func address(at offset: UInt64) -> String? {
        guard offset < addressCount else { return nil }
        return formatIPv4(networkAddress &+ UInt32(offset))
    }

    private static func mask(_ prefix: Int) -> UInt32 {
        guard prefix > 0 else { return 0 }
        if prefix >= 32 { return UInt32.max }
        return UInt32.max << UInt32(32 - prefix)
    }
}

internal struct IPv4InterfaceInfo: Equatable, Sendable {
    let address: String
    let prefixLength: Int
}

/// Discover attached IP networks, excluding public, loopback and link-local
/// ranges. Networks broader than `minNetmask` are constrained to that prefix.
internal func findIPv4Networks(
    minNetmask: Int,
    interfaces: [IPv4InterfaceInfo] = systemIPv4Interfaces()
) -> Set<IPv4Network> {
    let constrainedMinimum = min(32, max(0, minNetmask))
    var networks = Set<IPv4Network>()
    for interface in interfaces {
        guard let value = parseIPv4(interface.address),
              isPrivateIPv4(value),
              !isLoopbackIPv4(value),
              !isLinkLocalIPv4(value)
        else { continue }

        let prefix = max(interface.prefixLength, constrainedMinimum)
        networks.insert(IPv4Network(address: interface.address, prefixLength: prefix))
    }
    return networks
}

/// Discover all host IPv4 addresses, excluding loopback and link-local ranges.
/// Public addresses are deliberately retained here because SSDP multicast may
/// legitimately be emitted on such an interface; only network *scanning* is
/// restricted to private ranges.
internal func findIPv4Addresses(
    interfaces: [IPv4InterfaceInfo] = systemIPv4Interfaces()
) -> Set<String> {
    Set(interfaces.compactMap { interface in
        guard let value = parseIPv4(interface.address),
              !isLoopbackIPv4(value),
              !isLinkLocalIPv4(value)
        else { return nil }
        return interface.address
    })
}

internal func parseIPv4(_ string: String) -> UInt32? {
    let parts = string.split(separator: ".", omittingEmptySubsequences: false)
    guard parts.count == 4 else { return nil }
    var value: UInt32 = 0
    for part in parts {
        guard !part.isEmpty, let octet = UInt8(part) else { return nil }
        value = (value << 8) | UInt32(octet)
    }
    return value
}

internal func formatIPv4(_ value: UInt32) -> String {
    [24, 16, 8, 0].map { String((value >> UInt32($0)) & 0xff) }.joined(separator: ".")
}

private func isPrivateIPv4(_ value: UInt32) -> Bool {
    let first = (value >> 24) & 0xff
    let second = (value >> 16) & 0xff
    return first == 10 || (first == 172 && (16...31).contains(second)) || (first == 192 && second == 168)
}

private func isLoopbackIPv4(_ value: UInt32) -> Bool { (value >> 24) == 127 }
private func isLinkLocalIPv4(_ value: UInt32) -> Bool {
    ((value >> 24) & 0xff) == 169 && ((value >> 16) & 0xff) == 254
}

internal func systemIPv4Interfaces() -> [IPv4InterfaceInfo] {
    var head: UnsafeMutablePointer<ifaddrs>?
    guard getifaddrs(&head) == 0, let first = head else { return [] }
    defer { freeifaddrs(head) }

    var output: [IPv4InterfaceInfo] = []
    var cursor: UnsafeMutablePointer<ifaddrs>? = first
    while let current = cursor {
        defer { cursor = current.pointee.ifa_next }
        guard let addressPointer = current.pointee.ifa_addr,
              Int32(addressPointer.pointee.sa_family) == AF_INET
        else { continue }

        let sin = UnsafeRawPointer(addressPointer)
            .assumingMemoryBound(to: sockaddr_in.self).pointee
        var address = sin.sin_addr
        var chars = [CChar](repeating: 0, count: Int(INET_ADDRSTRLEN))
        guard inet_ntop(AF_INET, &address, &chars, socklen_t(INET_ADDRSTRLEN)) != nil else {
            continue
        }
        let addressString = String(cString: chars)

        var prefix = 32
        if let maskPointer = current.pointee.ifa_netmask {
            let maskSin = UnsafeRawPointer(maskPointer)
                .assumingMemoryBound(to: sockaddr_in.self).pointee
            prefix = Int(UInt32(bigEndian: maskSin.sin_addr.s_addr).nonzeroBitCount)
        }
        output.append(.init(address: addressString, prefixLength: prefix))
    }
    return output
}

// MARK: - TCP network scanning

/// Check whether a TCP connection can be made to the given IP and port.
internal func checkIPAndPort(
    _ ipAddress: String,
    port: UInt16,
    timeout: TimeInterval
) -> Bool {
    guard parseIPv4(ipAddress) != nil else { return false }
    let fd = socket(AF_INET, streamSocketType, 0)
    guard fd >= 0 else { return false }
    defer { systemClose(fd) }

    let currentFlags = fcntl(fd, F_GETFL, 0)
    if currentFlags >= 0 { _ = fcntl(fd, F_SETFL, currentFlags | O_NONBLOCK) }

    var target = sockaddr_in()
    target.sin_family = sa_family_t(AF_INET)
    target.sin_port = port.bigEndian
    guard ipAddress.withCString({ inet_pton(AF_INET, $0, &target.sin_addr) }) == 1 else {
        return false
    }

    let connected = withUnsafePointer(to: &target) { pointer in
        pointer.withMemoryRebound(to: sockaddr.self, capacity: 1) {
            connect(fd, $0, socklen_t(MemoryLayout<sockaddr_in>.size))
        }
    }
    if connected == 0 { return true }
    guard errno == EINPROGRESS else { return false }

    var descriptor = pollfd(fd: fd, events: Int16(POLLOUT), revents: 0)
    let millis = Int32(max(0, min(Double(Int32.max), timeout * 1000)))
    guard systemPoll(&descriptor, 1, millis) > 0,
          (descriptor.revents & Int16(POLLOUT)) != 0
    else { return false }

    var socketError: Int32 = 0
    var length = socklen_t(MemoryLayout<Int32>.size)
    guard getsockopt(fd, SOL_SOCKET, SO_ERROR, &socketError, &length) == 0 else { return false }
    return socketError == 0
}

/// Check if this is a Sonos device by trying to read a device property.
internal func isSonos(_ ipAddress: String) -> Bool {
    do {
        let device = try SoCoConfig.socoFactory(ipAddress)
        _ = try device.isVisible()
        return true
    } catch {
        // The exception is intentionally unimportant here. A scan probes many
        // ordinary hosts and failure simply means "not a Sonos player".
        return false
    }
}

/// Thread-safe address source and result sink used by the scan workers.
private final class ScanState: @unchecked Sendable {
    private let lock = NSLock()
    private let networks: [IPv4Network]
    private var networkIndex = 0
    private var addressOffset: UInt64 = 0
    private var stopped = false
    private var found: [String] = []

    init(networks: [IPv4Network]) { self.networks = networks }

    func next() -> String? {
        lock.lock()
        defer { lock.unlock() }
        guard !stopped else { return nil }
        while networkIndex < networks.count {
            let network = networks[networkIndex]
            if let address = network.address(at: addressOffset) {
                addressOffset += 1
                return address
            }
            networkIndex += 1
            addressOffset = 0
        }
        return nil
    }

    func record(_ address: String, exhaustive: Bool) {
        lock.lock()
        defer { lock.unlock() }
        guard exhaustive || !stopped else { return }
        if !found.contains(address) { found.append(address) }
        if !exhaustive { stopped = true }
    }

    var results: [String] {
        lock.lock()
        defer { lock.unlock() }
        return found
    }
}

/// Equivalent of SoCo's `_sonos_scan_worker_thread`, generalized so the test
/// suite can inject deterministic port/Sonos checks without monkeypatching BSD
/// sockets.
internal func scanIPAddresses(
    networks: [IPv4Network],
    maxThreads: Int,
    socketTimeout: TimeInterval,
    multiHousehold: Bool,
    portChecker: @escaping @Sendable (String, TimeInterval) -> Bool,
    sonosChecker: @escaping @Sendable (String) -> Bool
) -> [String] {
    let totalCount = networks.reduce(UInt64(0)) { partial, network in
        let (sum, overflow) = partial.addingReportingOverflow(network.addressCount)
        return overflow ? UInt64.max : sum
    }
    let workerCount = min(max(0, maxThreads), Int(min(UInt64(Int.max), totalCount)))
    guard workerCount > 0 else { return [] }

    let state = ScanState(networks: networks)
    let group = DispatchGroup()
    let queue = DispatchQueue(label: "SoCoKit.discovery.scan", attributes: .concurrent)

    for _ in 0..<workerCount {
        group.enter()
        queue.async {
            defer { group.leave() }
            while let ipAddress = state.next() {
                if portChecker(ipAddress, socketTimeout), sonosChecker(ipAddress) {
                    state.record(ipAddress, exhaustive: multiHousehold)
                    if !multiHousehold { return }
                }
            }
        }
    }
    group.wait()
    return state.results
}

// MARK: - SSDP socket helpers

private var datagramSocketType: Int32 {
    #if os(Linux)
    return Int32(SOCK_DGRAM.rawValue)
    #else
    return SOCK_DGRAM
    #endif
}

private var streamSocketType: Int32 {
    #if os(Linux)
    return Int32(SOCK_STREAM.rawValue)
    #else
    return SOCK_STREAM
    #endif
}

private func createDiscoverySocket(interfaceAddress: String) -> Int32? {
    let fd = socket(AF_INET, datagramSocketType, Int32(IPPROTO_UDP))
    guard fd >= 0 else { return nil }

    // UPnP v1.0 requires a TTL of 4.
    var ttl: UInt8 = 4
    guard setsockopt(
        fd, Int32(IPPROTO_IP), IP_MULTICAST_TTL,
        &ttl, socklen_t(MemoryLayout<UInt8>.size)
    ) == 0 else {
        systemClose(fd)
        return nil
    }

    var interface = in_addr()
    guard interfaceAddress.withCString({ inet_pton(AF_INET, $0, &interface) }) == 1,
          setsockopt(
            fd, Int32(IPPROTO_IP), IP_MULTICAST_IF,
            &interface, socklen_t(MemoryLayout<in_addr>.size)
          ) == 0
    else {
        systemClose(fd)
        return nil
    }
    return fd
}

private func sendDiscovery(fd: Int32) -> Bool {
    var destination = sockaddr_in()
    destination.sin_family = sa_family_t(AF_INET)
    destination.sin_port = SoCoConfig.discoveryPort.bigEndian
    guard SoCoConfig.discoveryAddress.withCString({
        inet_pton(AF_INET, $0, &destination.sin_addr)
    }) == 1 else { return false }

    let bytes = Array(Discovery.playerSearch.utf8)
    let sent = bytes.withUnsafeBytes { rawBuffer in
        withUnsafePointer(to: &destination) { pointer in
            pointer.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                sendto(
                    fd,
                    rawBuffer.baseAddress,
                    rawBuffer.count,
                    0,
                    $0,
                    socklen_t(MemoryLayout<sockaddr_in>.size)
                )
            }
        }
    }
    return sent == bytes.count
}

private struct DiscoveryResponse {
    let data: [UInt8]
    let ipAddress: String
}

private func receiveDiscovery(fd: Int32) -> DiscoveryResponse? {
    var bytes = [UInt8](repeating: 0, count: 1024)
    var sender = sockaddr_storage()
    var senderLength = socklen_t(MemoryLayout<sockaddr_storage>.size)
    let count = bytes.withUnsafeMutableBytes { buffer in
        withUnsafeMutablePointer(to: &sender) { senderPointer in
            senderPointer.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                recvfrom(fd, buffer.baseAddress, buffer.count, 0, $0, &senderLength)
            }
        }
    }
    guard count > 0 else { return nil }
    bytes.removeSubrange(Int(count)..<bytes.count)

    let family = withUnsafePointer(to: &sender) {
        $0.withMemoryRebound(to: sockaddr.self, capacity: 1) { $0.pointee.sa_family }
    }
    guard Int32(family) == AF_INET else { return nil }
    let sin = withUnsafePointer(to: &sender) {
        $0.withMemoryRebound(to: sockaddr_in.self, capacity: 1) { $0.pointee }
    }
    let hostValue = UInt32(bigEndian: sin.sin_addr.s_addr)
    return DiscoveryResponse(data: bytes, ipAddress: formatIPv4(hostValue))
}

private func containsBytes(_ haystack: [UInt8], _ needle: [UInt8]) -> Bool {
    guard !needle.isEmpty else { return true }
    guard needle.count <= haystack.count else { return false }
    if needle.count == 1 { return haystack.contains(needle[0]) }
    for index in 0...(haystack.count - needle.count) {
        if haystack[index..<(index + needle.count)].elementsEqual(needle) { return true }
    }
    return false
}

private func systemClose(_ fd: Int32) {
    #if os(Linux)
    _ = Glibc.close(fd)
    #else
    _ = Darwin.close(fd)
    #endif
}

private func systemPoll(
    _ fds: UnsafeMutablePointer<pollfd>?,
    _ count: nfds_t,
    _ timeout: Int32
) -> Int32 {
    #if os(Linux)
    return Glibc.poll(fds, count, timeout)
    #else
    return Darwin.poll(fds, count, timeout)
    #endif
}

private final class LockedSet<Element: Hashable>: @unchecked Sendable {
    private let lock = NSLock()
    private var storage = Set<Element>()
    func insert(_ value: Element) {
        lock.lock(); storage.insert(value); lock.unlock()
    }
    var value: Set<Element> {
        lock.lock(); defer { lock.unlock() }; return storage
    }
}

/// Internal matcher separated from network discovery so the original `by_name`
/// behavior is directly testable without opening multicast sockets.
internal func findByName(_ name: String, in devices: Set<SoCo>) throws -> SoCo? {
    for device in devices where try device.playerName() == name { return device }
    return nil
}

// MARK: - Python-style discovery convenience functions

/// Discover Sonos zones on the local network.
///
/// This free-function spelling mirrors `soco.discovery.discover`; new Swift code
/// may prefer the namespaced `Discovery.discover` form.
public func discover(
    timeout: TimeInterval = 5,
    includeInvisible: Bool = false,
    interfaceAddress: String? = nil,
    householdID: String = "Sonos",
    allowNetworkScan: Bool = false,
    networkScanOptions: Discovery.NetworkScanOptions = .init()
) throws -> Set<SoCo>? {
    try Discovery.discover(
        timeout: timeout,
        includeInvisible: includeInvisible,
        interfaceAddress: interfaceAddress,
        householdID: householdID,
        allowNetworkScan: allowNetworkScan,
        networkScanOptions: networkScanOptions
    )
}

/// Return any visible SoCo device, reusing a known instance when possible.
public func anySoCo(
    allowNetworkScan: Bool = false,
    networkScanOptions: Discovery.NetworkScanOptions = .init()
) throws -> SoCo? {
    try Discovery.anySoCo(allowNetworkScan: allowNetworkScan, networkScanOptions: networkScanOptions)
}

/// Return a visible Sonos device by player name.
public func byName(
    _ name: String,
    allowNetworkScan: Bool = false,
    networkScanOptions: Discovery.NetworkScanOptions = .init()
) throws -> SoCo? {
    try Discovery.byName(name, allowNetworkScan: allowNetworkScan, networkScanOptions: networkScanOptions)
}

/// Scan attached networks for Sonos devices when SSDP multicast is unavailable.
public func scanNetwork(
    includeInvisible: Bool = false,
    options: Discovery.NetworkScanOptions = .init()
) throws -> Set<SoCo>? {
    try Discovery.scanNetwork(includeInvisible: includeInvisible, options: options)
}

/// Scan for zones in one Sonos household.
public func scanNetworkByHouseholdID(
    _ householdID: String,
    includeInvisible: Bool = false,
    options: Discovery.NetworkScanOptions = .init()
) throws -> Set<SoCo>? {
    try Discovery.scanNetworkByHouseholdID(householdID, includeInvisible: includeInvisible, options: options)
}

/// Find all Sonos household IDs on attached networks.
public func scanNetworkGetHouseholdIDs(
    options: Discovery.NetworkScanOptions = .init()
) throws -> Set<String> {
    try Discovery.scanNetworkGetHouseholdIDs(options: options)
}

/// Find a visible zone by name using network scanning.
public func scanNetworkGetByName(
    _ name: String,
    householdID: String? = nil,
    options: Discovery.NetworkScanOptions = .init()
) throws -> SoCo? {
    try Discovery.scanNetworkGetByName(name, householdID: householdID, options: options)
}

/// Find any visible zone using network scanning.
public func scanNetworkAnySoCo(
    householdID: String? = nil,
    options: Discovery.NetworkScanOptions = .init()
) throws -> SoCo? {
    try Discovery.scanNetworkAnySoCo(householdID: householdID, options: options)
}

/// Return the subset of Sonos objects which currently respond to visibility checks.
public func contactable(_ speakers: Set<SoCo>?) -> Set<SoCo> {
    Discovery.contactable(speakers)
}
